<?php

use Illuminate\Database\Seeder;

class MasterDatasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	// 削除する場合、行は消さずに`deleted_at`に日付を入れてください
		$data = [
			['type' => 'order_status', 'value' => 1, 'name' => '保存', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'order_status', 'value' => 2, 'name' => '発注済', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'order_status', 'value' => 3, 'name' => '受領完了', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'order_status', 'value' => 4, 'name' => '作業開始', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_material', 'value' => 1, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_material', 'value' => 2, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_material', 'value' => 3, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_color', 'value' => 1, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_color', 'value' => 2, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_color', 'value' => 3, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_1', 'value' => 1, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_1', 'value' => 2, 'name' => '①', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_1', 'value' => 3, 'name' => '❶', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_2', 'value' => 1, 'name' => '2', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_2', 'value' => 2, 'name' => '②', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_2', 'value' => 3, 'name' => '❷', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_3', 'value' => 1, 'name' => '3', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_3', 'value' => 2, 'name' => '③', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_3', 'value' => 3, 'name' => '❸', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_4', 'value' => 1, 'name' => '4', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_4', 'value' => 2, 'name' => '④', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_4', 'value' => 3, 'name' => '❹', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_5', 'value' => 1, 'name' => '5', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_5', 'value' => 2, 'name' => '⑤', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_5', 'value' => 3, 'name' => '❺', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_6', 'value' => 1, 'name' => '6', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_6', 'value' => 2, 'name' => '⑥', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_6', 'value' => 3, 'name' => '❻', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_7', 'value' => 1, 'name' => '7', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_7', 'value' => 2, 'name' => '⑦', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_7', 'value' => 3, 'name' => '❼', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_8', 'value' => 1, 'name' => '8', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_8', 'value' => 2, 'name' => '⑧', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_right_8', 'value' => 3, 'name' => '❽', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_1', 'value' => 1, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_1', 'value' => 2, 'name' => '①', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_1', 'value' => 3, 'name' => '❶', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_2', 'value' => 1, 'name' => '2', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_2', 'value' => 2, 'name' => '②', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_2', 'value' => 3, 'name' => '❷', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_3', 'value' => 1, 'name' => '3', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_3', 'value' => 2, 'name' => '③', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_3', 'value' => 3, 'name' => '❸', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_4', 'value' => 1, 'name' => '4', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_4', 'value' => 2, 'name' => '④', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_4', 'value' => 3, 'name' => '❹', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_5', 'value' => 1, 'name' => '5', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_5', 'value' => 2, 'name' => '⑤', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_5', 'value' => 3, 'name' => '❺', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_6', 'value' => 1, 'name' => '6', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_6', 'value' => 2, 'name' => '⑥', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_6', 'value' => 3, 'name' => '❻', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_7', 'value' => 1, 'name' => '7', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_7', 'value' => 2, 'name' => '⑦', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_7', 'value' => 3, 'name' => '❼', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_8', 'value' => 1, 'name' => '8', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_8', 'value' => 2, 'name' => '⑧', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_upper_left_8', 'value' => 3, 'name' => '❽', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_1', 'value' => 1, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_1', 'value' => 2, 'name' => '①', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_1', 'value' => 3, 'name' => '❶', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_2', 'value' => 1, 'name' => '2', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_2', 'value' => 2, 'name' => '②', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_2', 'value' => 3, 'name' => '❷', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_3', 'value' => 1, 'name' => '3', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_3', 'value' => 2, 'name' => '③', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_3', 'value' => 3, 'name' => '❸', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_4', 'value' => 1, 'name' => '4', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_4', 'value' => 2, 'name' => '④', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_4', 'value' => 3, 'name' => '❹', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_5', 'value' => 1, 'name' => '5', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_5', 'value' => 2, 'name' => '⑤', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_5', 'value' => 3, 'name' => '❺', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_6', 'value' => 1, 'name' => '6', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_6', 'value' => 2, 'name' => '⑥', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_6', 'value' => 3, 'name' => '❻', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_7', 'value' => 1, 'name' => '7', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_7', 'value' => 2, 'name' => '⑦', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_7', 'value' => 3, 'name' => '❼', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_8', 'value' => 1, 'name' => '8', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_8', 'value' => 2, 'name' => '⑧', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_right_8', 'value' => 3, 'name' => '❽', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_1', 'value' => 1, 'name' => '1', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_1', 'value' => 2, 'name' => '①', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_1', 'value' => 3, 'name' => '❶', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_2', 'value' => 1, 'name' => '2', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_2', 'value' => 2, 'name' => '②', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_2', 'value' => 3, 'name' => '❷', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_3', 'value' => 1, 'name' => '3', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_3', 'value' => 2, 'name' => '③', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_3', 'value' => 3, 'name' => '❸', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_4', 'value' => 1, 'name' => '4', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_4', 'value' => 2, 'name' => '④', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_4', 'value' => 3, 'name' => '❹', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_5', 'value' => 1, 'name' => '5', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_5', 'value' => 2, 'name' => '⑤', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_5', 'value' => 3, 'name' => '❺', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_6', 'value' => 1, 'name' => '6', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_6', 'value' => 2, 'name' => '⑥', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_6', 'value' => 3, 'name' => '❻', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_7', 'value' => 1, 'name' => '7', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_7', 'value' => 2, 'name' => '⑦', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_7', 'value' => 3, 'name' => '❼', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_8', 'value' => 1, 'name' => '8', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_8', 'value' => 2, 'name' => '⑧', 'created_at' => now(), 'deleted_at' => null],
			['type' => 'tooth_bottom_left_8', 'value' => 3, 'name' => '❽', 'created_at' => now(), 'deleted_at' => null],

		];
		DB::table('master_datas')->truncate();
        DB::table('master_datas')->insert($data);
    }
}
